# Generated by Django 5.1.7 on 2025-03-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='firs_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='quialification',
            new_name='qualification',
        ),
    ]
